// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLO6NJW2K5LYVSgUDBZgAv9u0WGIa_h7Q',
    appId: '1:73354898938:web:c477ff2bfc2af624a08843',
    messagingSenderId: '73354898938',
    projectId: 'splitsync-6b39b',
    authDomain: 'splitsync-6b39b.firebaseapp.com',
    storageBucket: 'splitsync-6b39b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6afM0drX8djp50jmEdvNzbtm9exjb0K4',
    appId: '1:73354898938:android:4427c01313844028a08843',
    messagingSenderId: '73354898938',
    projectId: 'splitsync-6b39b',
    storageBucket: 'splitsync-6b39b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmaM3FOsVNOIPZ5VqDDAjQSOw5U04plHA',
    appId: '1:73354898938:ios:35da2ada72a1423aa08843',
    messagingSenderId: '73354898938',
    projectId: 'splitsync-6b39b',
    storageBucket: 'splitsync-6b39b.firebasestorage.app',
    iosBundleId: 'com.example.splitsync',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmaM3FOsVNOIPZ5VqDDAjQSOw5U04plHA',
    appId: '1:73354898938:ios:35da2ada72a1423aa08843',
    messagingSenderId: '73354898938',
    projectId: 'splitsync-6b39b',
    storageBucket: 'splitsync-6b39b.firebasestorage.app',
    iosBundleId: 'com.example.splitsync',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBLO6NJW2K5LYVSgUDBZgAv9u0WGIa_h7Q',
    appId: '1:73354898938:web:a11b507388e87f1ca08843',
    messagingSenderId: '73354898938',
    projectId: 'splitsync-6b39b',
    authDomain: 'splitsync-6b39b.firebaseapp.com',
    storageBucket: 'splitsync-6b39b.firebasestorage.app',
  );
}
